"""
HimcastInvoiceTemplate - Invoice template for Himgiri Castings Pvt. Ltd -G
Generated: 2025-12-22 22:52:54
"""

import re
from typing import List, Dict
from .base_template import BaseTemplate


class HimcastInvoiceTemplate(BaseTemplate):
    """
    Invoice template for Himgiri Castings Pvt. Ltd -G.
    Generated by Template Generator.
    """

    name = "Himcast Invoice"
    description = "Commercial Invoice"
    client = "Himgiri Castings Pvt. Ltd -G"
    version = "1.0.0"
    enabled = True

    extra_columns = ['country']

    def can_process(self, text: str) -> bool:
        """Check if this template can process the invoice."""
        text_lower = text.lower()
        indicators = ['himgiri castings pvt. ltd -g', 'gstin : 30aaach7559j1zj', 'pt', 'as']
        return any(ind in text_lower for ind in indicators)

    def get_confidence_score(self, text: str) -> float:
        """Return confidence score for template matching."""
        if not self.can_process(text):
            return 0.0

        score = 0.5
        text_lower = text.lower()

        # Add confidence based on multiple indicators
        indicators = ['himgiri castings pvt. ltd -g', 'gstin : 30aaach7559j1zj', 'pt', 'as']
        for ind in indicators:
            if ind in text_lower:
                score += 0.15

        # Check for invoice pattern
        if re.search(r'INV\.?\s*(?:#|NO\.?)?\s*:?\s*([A-Z0-9][\w\-/]+)', text, re.IGNORECASE):
            score += 0.1

        return min(score, 1.0)

    def extract_invoice_number(self, text: str) -> str:
        """Extract invoice number."""
        pattern = r'INV\.?\s*(?:#|NO\.?)?\s*:?\s*([A-Z0-9][\w\-/]+)'
        match = re.search(pattern, text, re.IGNORECASE)
        if match:
            return match.group(1).strip() if match.lastindex else match.group(0).strip()
        return "UNKNOWN"

    def extract_project_number(self, text: str) -> str:
        """Extract project number."""
        pattern = r'\b(400\d{5})\b'
        match = re.search(pattern, text, re.IGNORECASE)
        if match:
            return match.group(1).strip() if match.lastindex else match.group(0).strip()
        return "UNKNOWN"

    def extract_manufacturer_name(self, text: str) -> str:
        """Extract manufacturer name."""
        return "Himgiri Castings Pvt. Ltd -G"

    def extract_line_items(self, text: str) -> List[Dict]:
        """Extract line items from invoice."""
        line_items = []
        seen_items = set()

        # Line item pattern
        pattern = re.compile(r'([A-Z0-9][\\w\\-]+)\\s+(\\d+)\\s+\\$?([\\d,.]+)', re.MULTILINE | re.IGNORECASE)

        for match in pattern.finditer(text):
            try:
                groups = match.groups()
                part_number = groups[0] if len(groups) > 0 else ''
                quantity = groups[1] if len(groups) > 1 else ''
                total_price = groups[2] if len(groups) > 2 else ''

                # Clean numeric values
                quantity = re.sub(r'[^\d.]', '', str(quantity))
                total_price = re.sub(r'[^\d.]', '', str(total_price))

                # Deduplication
                item_key = f"{part_number}_{quantity}_{total_price}"
                if item_key not in seen_items and part_number:
                    seen_items.add(item_key)

                    qty = float(quantity) if quantity else 1
                    price = float(total_price) if total_price else 0
                    unit_price = price / qty if qty > 0 else price

                    line_items.append({
                        'part_number': part_number,
                        'quantity': quantity,
                        'total_price': total_price,
                        'unit_price': f"{unit_price:.2f}",
                    })

            except (ValueError, IndexError):
                continue

        return line_items

    def is_packing_list(self, text: str) -> bool:
        """Check if document is a packing list."""
        text_lower = text.lower()
        if 'packing list' in text_lower or 'packing slip' in text_lower:
            if 'invoice' not in text_lower:
                return True
        return False
