"""
MmcitAsTemplate - Auto-generated template for mmcité a.s
Generated by TariffMill AI Template Builder
"""

import re
from typing import List, Dict
from .base_template import BaseTemplate


class MmcitAsTemplate(BaseTemplate):
    """
    Template for mmcité a.s invoices.

    Auto-generated patterns - review and adjust as needed.
    """

    name = "Mmcit As"
    description = "Invoice template for mmcité a.s"
    client = "mmcité a.s"
    version = "1.0.0"

    enabled = True

    extra_columns = ['item_code', 'project_code', 'unit_price_czk', 'vat_rate', 'total_price_usd']

    def can_process(self, text: str) -> bool:
        """Check if this template can process the given invoice."""
        return 'invoice n.' in text.lower() and 'variable symbol:' in text.lower() and 'project n.:' in text.lower() and 'mmcité a.s' in text.lower() and 'vat cz27670864' in text.lower()

    def get_confidence_score(self, text: str) -> float:
        """Return confidence score for template matching."""
        if not self.can_process(text):
            return 0.0

        score = 0.5
        # Add points for each indicator found
        indicators = ['Invoice n.', 'variable symbol:', 'project n.:', 'mmcité a.s', 'VAT CZ27670864']
        for indicator in indicators:
            if indicator.lower() in text.lower():
                score += 0.1

        return min(score, 1.0)

    def extract_invoice_number(self, text: str) -> str:
        """Extract invoice number."""
        patterns = [
            r'Invoice n\. (\d+)',
        ]

        for pattern in patterns:
            match = re.search(pattern, text, re.IGNORECASE)
            if match:
                return match.group(1).strip()

        return "UNKNOWN"

    def extract_project_number(self, text: str) -> str:
        """Extract project number."""
        patterns = [
            r'project n\.: ([A-Z0-9]+)',
        ]

        for pattern in patterns:
            match = re.search(pattern, text, re.IGNORECASE)
            if match:
                return match.group(1).strip()

        return "UNKNOWN"

    def extract_line_items(self, text: str) -> List[Dict]:
        """Extract line items from invoice."""
        line_items = []
        seen_items = set()

        # Line item pattern - adjust as needed
        line_pattern = re.compile(
            r'([A-Z0-9-]+)\s+([A-Z0-9]+)\s+([\d,]+)\s+ks\s+([\d,]+\.\d{2})\s+CZK\s+(\d+)\s+([\d,]+\.\d{2})\s+USD',
            re.MULTILINE | re.IGNORECASE
        )

        for match in line_pattern.finditer(text):
            try:
                item = {
                        'item_code': match.group(1),
                        'project_code': match.group(2),
                        'quantity': match.group(3),
                        'unit_price_czk': match.group(4),
                        'vat_rate': match.group(5),
                        'total_price_usd': match.group(6),
                    }

                # Create deduplication key
                item_key = f"{item.get('part_number', '')}_{item.get('quantity', '')}"

                if item_key not in seen_items:
                    seen_items.add(item_key)
                    line_items.append(item)

            except (IndexError, AttributeError):
                continue

        return line_items
