"""
TestTemplate - Auto-generated invoice template
Generated: 2025-12-19 23:00:28
Company: Unknown Supplier
"""

import re
from typing import List, Dict
from .base_template import BaseTemplate


class TestTemplate(BaseTemplate):
    """
    Invoice template for Unknown Supplier.
    Auto-generated by TariffMill Auto Template Builder.
    """

    name = "Test"
    description = "Invoice template for Unknown Supplier"
    client = "Unknown Supplier"
    version = "1.0.0"
    enabled = True

    extra_columns = ['unit_price', 'net_weight']

    def can_process(self, text: str) -> bool:
        """Check if this template can process the invoice."""
        return 'variable symbol' in text.lower() and 'name of project' in text.lower() and 'date of issue' in text.lower()

    def get_confidence_score(self, text: str) -> float:
        """Return confidence score for this template."""
        if not self.can_process(text):
            return 0.0

        score = 0.5
        # Add confidence based on pattern matches
        if re.search(r'(?:Proforma\\s+)?[Ii]nvoice\\s+(?:[Nn]o\\.?|[Nn]umber|#)\\s*:?\\s*([A-Z0-9][\\w\\-/]+)', text, re.IGNORECASE):
            score += 0.2
        if re.search(r'[Pp]roject\\s*:?\\s*(\\w+[\\-\\d]+\\w*)', text, re.IGNORECASE):
            score += 0.2
        return min(score, 1.0)

    def extract_invoice_number(self, text: str) -> str:
        """Extract invoice number."""
        pattern = r'(?:Proforma\\s+)?[Ii]nvoice\\s+(?:[Nn]o\\.?|[Nn]umber|#)\\s*:?\\s*([A-Z0-9][\\w\\-/]+)'
        match = re.search(pattern, text, re.IGNORECASE)
        if match:
            return match.group(1).strip()
        return "UNKNOWN"

    def extract_project_number(self, text: str) -> str:
        """Extract project number."""
        pattern = r'[Pp]roject\\s*:?\\s*(\\w+[\\-\\d]+\\w*)'
        match = re.search(pattern, text, re.IGNORECASE)
        if match:
            return match.group(1).strip().upper()
        return "UNKNOWN"

    def extract_manufacturer_name(self, text: str) -> str:
        """Extract manufacturer/supplier name."""
        return "Unknown Supplier"

    def extract_line_items(self, text: str) -> List[Dict]:
        """Extract line items from invoice."""
        line_items = []
        seen_items = set()

        lines = text.split('\n')

        # Primary line item pattern
        pattern = re.compile(r'^([A-Z0-9][\\w\\-\\.]+)\\s+.{10,50}\\s+(\\d+(?:[,\\.]\\d+)?)\\s+[\\$€]?([\\d,]+\\.?\\d*)', re.IGNORECASE)

        for line in lines:
            line = line.strip()
            if not line:
                continue

            match = pattern.match(line)
            if match:
                groups = match.groups()

                part_number = groups[0] if len(groups) > 0 else ''
                quantity = groups[1] if len(groups) > 1 else '1'
                total_price = groups[-1] if len(groups) > 2 else groups[1] if len(groups) > 1 else '0'

                # Clean numeric values
                quantity = re.sub(r'[^\d.]', '', str(quantity))
                total_price = re.sub(r'[^\d.]', '', str(total_price))

                # Deduplication
                item_key = f"{part_number}_{quantity}_{total_price}"
                if item_key not in seen_items and part_number:
                    seen_items.add(item_key)

                    qty = float(quantity) if quantity else 1
                    price = float(total_price) if total_price else 0
                    unit_price = price / qty if qty > 0 else price

                    line_items.append({
                        'part_number': part_number,
                        'quantity': quantity,
                        'total_price': total_price,
                        'unit_price': f"{unit_price:.2f}",
                    })

        return line_items

    def is_packing_list(self, text: str) -> bool:
        """Check if document is a packing list."""
        text_lower = text.lower()
        if 'packing list' in text_lower or 'packing slip' in text_lower:
            if 'invoice' not in text_lower:
                return True
        return False
